name: Build Docker & Charts

on:
  workflow_dispatch:
    inputs:
      docker_build_job_name:
        description: "Name of the product's job that build and push the application's docker image"
        type: string
        required: true
        default: "docker-build-and-push"

jobs:
  circleci-docker-build:
    name: "Trigger CircleCI Build"
    runs-on: ubuntu-22.04
    steps:
      - name: "Trigger CircleCI Build"
        uses: labforward/platform-gha/circleci/trigger@1
        with:
          cci_token: ${{ secrets.CCI_TOKEN }}
          docker_build_job_name: ${{ inputs.docker_build_job_name }}
